### Get all universities
GET http://127.0.0.1:5000/api/universitylist
Content-Type: application/json

Response: 
{
    "message": "Universities retrieved",
    "type": "success",
    "universities": [     
        {
            "id": 1,
            "name": "Politecnico di Torino"
        },
        {
            "id": 2,
            "name": "Politecnico di Milano"
        },
        {
            "id": 3,
            "name": "Politecnico di Bari"
        },
        {
            "id": 4,
            "name": "Politecnico di Bari"
        },
        {
            "id": 5,
            "name": "Politecnico di Bari"
        },
        {
            "id": 6,
            "name": "Politecnico di Bari"
        },
        {
            "id": 7,
            "name": "Politecnico di Bari"
        },
        {
            "id": 8,
            "name": "Politecnico di Bari"
        },
        {
            "id": 9,
            "name": "Politecnico di Bari"
        },
        {
            "id": 11,
            "name": "Prova"
        },
        {
            "id": 34,
            "name": "Boh"
        }
    ]
}

